LICENSE
README.md

Note: Sections can be moved to separate pages (in a `docs/` directory for example) as we document more stuff here.

docs: Add README, LICENSE

---

.github/workflows/go.yml
Makefile
README.md
internal/config.go
internal/output.go
pkg/converter/converter.go

Initial CI pipeline
* Jobs run in parallel to speed up
* I added [golangci-lint](https://golangci-lint.run/) - I have made good experiences with it. It already catched two issues (a bug where an error value was not checked, and use of a deprecated Stdlib module).
I have also added a small `Makefile` to run the steps locally

ci: Initial config

---

renovate.json

This will configure Renovate to automatically merge updates that only do lockfile maintenance (updates that do not change the requirements) and patch level updates for versions > v0.x
Also:
- ignore golden-test files
- disable the dependency dashboard

chore(renovate): Auto-merge patch updates

---

pkg/converter/converter.go
tests/golden/101/manifests/nginx-mpi-deployment.yaml
tests/golden/101/manifests/nginx-mpi-env-secret.yaml
tests/golden/101/manifests/nginx-mpi-service.yaml
tests/golden/demo/manifests/portal-mpi-8001-ingress.yaml
tests/golden/demo/manifests/portal-mpi-9001-ingress.yaml
tests/golden/demo/manifests/portal-mpi-claim0-persistentvolumeclaim.yaml
tests/golden/demo/manifests/portal-mpi-deployment.yaml
tests/golden/demo/manifests/portal-mpi-env-secret.yaml
tests/golden/demo/manifests/portal-mpi-service.yaml

Use separate labels for the compose-service name and the "sub" (derived from the ref).
The reason for this is that with a single label it is impossible to correctly find out which part is the compose-service name and which is the sub, e.g. in "portal-foo-bar" the compose-service name could be "portal" (with sub "foo-bar") or "portal-foo" (with sub "bar") or even "portal-foo-bar". Being able to correctly distinguish between compose-service name and sub is important for displaying information in the Web UI.
This change fixes this by using two separate labels. The same labels are used in the K8s service spec as selectors, which should work fine.

Change: Use separate labels for compose-service and sub

---

README.md
docs/conversion.md
pkg/converter/converter.go
pkg/util/stringutils.go
tests/golden/101/manifests/nginx-mpi-deployment.yaml
tests/golden/demo/docker-compose-prod.yml
tests/golden/demo/manifests/mongo-statefulset.yaml
tests/golden/demo/manifests/portal-mpi-deployment.yaml

I've added some magic.
* livenessProbe is enabled by default (but can be disabled).
* startupProbe is also enabled by default and uses the same settings as the livenessProbe, except for periodSeconds and failureThreshold.
* readinessProbe is disabled by default
What do you think?

feat: Support for liveness/startup/readiness probes

---

pkg/converter/converter.go
tests/golden/demo/manifests/portal-mpi-8001-ingress.yaml
tests/golden/demo/manifests/portal-mpi-9001-ingress.yaml

The ingresses set up by k8ify were not correct when refSlug was set. This fixes it.

fix: Ingress service backend must include refSlug

---

docs/conversion.md
pkg/converter/converter.go
tests/golden/101/manifests/nginx-mpi-deployment.yaml
tests/golden/defaults/manifests/nginx-mpi-deployment.yaml
tests/golden/demo/manifests/mongo-statefulset.yaml
tests/golden/demo/manifests/portal-mpi-deployment.yaml

If imagePullPolicy is not set it defaults to "IfNotPresent", which can cause unexpected behavior because K8s might not fetch modified images from the registry. This is a problem for branch deployments where the image tag (=branch name) does not change.
This change fixes that by setting the imagePullPolicy to 'Always'.
Note that this does not necessarily fix all potential related issues with branch deployments; in particular pods still need to be manually restarted. K8s won't do this by default because the Deployment/StatefulSet doesn't change in this case.

fix: Set imagePullPolicy to 'Always'

---

README.md
docs/conversion.md
go.mod
go.sum
internal/cmdflags.go
main.go
pkg/converter/patcher.go

Add dummy annotation to force K8s to restart Pods. This is useful for images that change without getting new tags, as it is common for test/review branch deployments. 
This problem does not exist for images that get new tags, e.g. for prod deployments. In these cases this change will also add the dummy annotation, but it does not introduce any new restarts because it affects the same K8s objects that are changed anyway because of the new image tag.
The intended usage pattern in a CI/CD pipeline is:
```
docker build -t "${REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
[...]
k8ify "${K8IFY_ENVIRONMENT}" "${K8IFY_DEPLOYMENT}" --modified-image "${NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
```
As this parameter can be specified multiple times it can also cover use …

feat: Specify changed images to force restart

---

.github/workflows/dockerbuild.yml
Dockerfile

Add a CI job that builds a docker image and pushes it to dockerhub.
The base image is [appuio/oc](https://hub.docker.com/r/appuio/oc/), in order to have the necessary tooling to run CI jobs.
@mhutter  After a lot of trial and error :see_no_evil: I think it now does what I want.

ci: Add Docker Build job

---

pkg/converter/converter.go
pkg/util/stringutils.go
pkg/util/stringutils_test.go
tests/golden/101/manifests/nginx-oasp-deployment.yaml
tests/golden/101/manifests/nginx-oasp-env-secret.yaml
tests/golden/101/manifests/nginx-oasp-service.yaml
tests/golden/defaults/manifests/nginx-oasp-deployment.yaml
tests/golden/defaults/manifests/nginx-oasp-env-secret.yaml
tests/golden/defaults/manifests/nginx-oasp-service.yaml
tests/golden/demo/manifests/portal-oasp-8001-ingress.yaml
tests/golden/demo/manifests/portal-oasp-9001-ingress.yaml
tests/golden/demo/manifests/portal-oasp-claim0-persistentvolumeclaim.yaml
tests/golden/demo/manifests/portal-oasp-deployment.yaml
tests/golden/demo/manifests/portal-oasp-env-secret.yaml
tests/golden/demo/manifests/portal-oasp-service.yaml

Increase the per-character entropy of the ByteArrayToAlpha function by replacing it with a ByteArrayToAlphaNum function. The purpose of this change is to reduce the risk of colliding resource names due to colliding ref names. This change takes the risk of two refs colliding down from 1/4096 to 1/1213056. Note that the risk of collisions rises very quickly with more than two generated refs (birthday paradox) so this change is even more important in those cases.
ByteArrayToAlphaNum will produce [a-z] for the first character and [a-z0-9] for subsequent characters. It uses all the bits from the input exactly once, hence it does a 1:1 mapping from a byte array to a string. The output length only depends on the input length, not the input value; if the input value is low, it may get padded with …

fix: Reduce collision probability of ref generator

---

internal/output.go
tests/golden/101/manifests/nginx-oasp-env-secret.yaml
tests/golden/101/manifests/nginx-oasp-service.yaml
tests/golden/defaults/manifests/nginx-oasp-env-secret.yaml
tests/golden/defaults/manifests/nginx-oasp-service.yaml
tests/golden/demo/manifests/mongo-env-secret.yaml
tests/golden/demo/manifests/mongo-service.yaml
tests/golden/demo/manifests/mongo-statefulset.yaml
tests/golden/demo/manifests/portal-oasp-8001-ingress.yaml
tests/golden/demo/manifests/portal-oasp-9001-ingress.yaml
tests/golden/demo/manifests/portal-oasp-env-secret.yaml
tests/golden/demo/manifests/portal-oasp-service.yaml
tests/golden/storage/manifests/default-oasp-env-secret.yaml
tests/golden/storage/manifests/default-oasp-service.yaml
tests/golden/storage/manifests/default-oasp-statefulset.yaml
tests/golden/storage/manifests/default-shared-data-oas-persistentvolumeclaim.yaml
tests/golden/storage/manifests/default-shared-oasp-env-secret.yaml
tests/golden/storage/manifests/default-shared-oasp-service.yaml
tests/golden/storage/manifests/share-0-oasp-deployment.yaml
tests/golden/storage/manifests/share-0-oasp-env-secret.yaml
tests/golden/storage/manifests/share-0-oasp-service.yaml
tests/golden/storage/manifests/share-1-oasp-deployment.yaml
tests/golden/storage/manifests/share-1-oasp-env-secret.yaml
tests/golden/storage/manifests/share-1-oasp-service.yaml
tests/golden/storage/manifests/shared-data-oas-persistentvolumeclaim.yaml
tests/golden/storage/manifests/singleton-db-env-secret.yaml
tests/golden/storage/manifests/singleton-db-service.yaml
tests/golden/storage/manifests/singleton-db-statefulset.yaml

Do not reuse the yaml printer because doing so prints separators starting with the second file. This lead to race conditions in the test cases because the first file wasn't always the same.
Relevant code in the yaml printer: https://github.com/kubernetes/cli-runtime/blob/v0.26.1/pkg/printers/yaml.go#L49
Unfortunately that code is not smart enough to realize that it is being called with a different destination file every time, and thus the counter isn't correct for that file. This may be good enough for the k8s CLI use case but it is not good enough for our use case.
There is no way to disable that behavior, so we just create a new yaml printer instance for every document, which removes all the separators from the output files.

fix: Do not re-use yaml printer to avoid printing separators

---

go.mod
golden_test.go
internal/output.go
internal/prechecks.go
main.go
pkg/util/configutils.go

The compose project already uses logrus for logging, and it does what we need, so it seemed reasonable to use the same here.
Reusing the same library also allows us to reconfigure all logging (eg. for tests) in one go.
I replaced all output by logrus calls. I refrained from using `logrus.Fatal` (which prints the error message and then terminates the process with exit code 1), and left in all the explicit `os.Exit(1)` calls instead.
Preview of how it looks:
Ref: APPX-30

Use logrus for all logging

---

README.md
docs/conversion.md
pkg/converter/converter.go
pkg/util/configutils.go
tests/golden/demo/docker-compose-prod.yml
tests/golden/demo/manifests/portal-oasp-deployment.yaml

Add option to configure the pod's "spec.serviceAccountName" field.
This is useful for deploying applications that need to access the K8s API because with the help of this setting K8s mounts the ServiceAccount credentials into the pod.
This feature does not set up the ServiceAccount itself.

feat: Make pod spec.serviceAccountName configurable

---

pkg/converter/converter.go

Converters may log diagnostic infos to STDERR. So instead of reading the combined output, we only read their STDOUT, and just forward STDERR to ours.

fix: Only read STDOUT from converter commands

---

README.md
internal/prechecks.go
main.go
pkg/converter/converter.go
pkg/ir/ir.go
tests/golden/cluster-apps-domain.yml
tests/golden/cluster-apps-domain/compose.yml
tests/golden/cluster-apps-domain/manifests/nginx-oasp-deployment.yaml
tests/golden/cluster-apps-domain/manifests/nginx-oasp-ingress.yaml
tests/golden/cluster-apps-domain/manifests/nginx-oasp-service.yaml

Also see internal ticket APPX-27.
This PR adds a sanity check to verify that [exported domains aren't too long](https://community.letsencrypt.org/t/a-certificate-for-a-63-character-domain/78870), and adds support for using the target cluster's wildcard certificate, which works by creating an Ingress resource with the following spec:
```
spec:
tls:
- {}
```
(note that this is pretty much undocumented but seems to be officially supported. Of course this solves the problem of the long domain names because with the wildcard certificate we don't need to actually generate a certificate for these domains. And also obviously it will only work if the exposed domain is a direct subdomain covered by the wildcard cert)
However for this to work k8ify needs to know some more things about the target …

feat: Check domain name lengths and allow using cluster wildcard cert

---

go.mod
pkg/converter/converter.go
tests/golden/expose-http-and-plain.yml
tests/golden/expose-http-and-plain/compose.yml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-22-21-service.yaml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-443-service.yaml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-deployment.yaml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-ingress.yaml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-service.yaml

Fix an issue where an ingress would reference the wrong service object under certain conditions (more than one service object present).
This is actually fixed by upgrading to Go 1.22, since this problem was caused by weird handling of loop variables in older Go versions.

Fix: Ingress references wrong service under certain conditions

---

pkg/converter/converter.go
tests/golden/env-vars/compose.yml
tests/golden/env-vars/manifests/fooBar-oasp-deployment.yaml

fix: Secret references must be sorted to ensure stable output

---

README.md
docs/conversion.md
pkg/converter/converter.go
tests/golden/101/manifests/nginx-oasp-deployment.yaml
tests/golden/cluster-apps-domain/manifests/nginx-oasp-deployment.yaml
tests/golden/defaults/manifests/nginx-oasp-deployment.yaml
tests/golden/demo/docker-compose.yml
tests/golden/demo/manifests/mongo-statefulset.yaml
tests/golden/demo/manifests/portal-oasp-deployment.yaml
tests/golden/empty-env-vars-list/manifests/pinger-oasp-deployment.yaml
tests/golden/empty-env-vars-map/manifests/pinger-oasp-deployment.yaml
tests/golden/env-vars/manifests/fooBar-oasp-deployment.yaml
tests/golden/expose-http-and-plain/manifests/nginx-oasp-deployment.yaml
tests/golden/expose-plain/manifests/nginx-oasp-deployment.yaml
tests/golden/noports/manifests/pinger-oasp-deployment.yaml
tests/golden/parts-ingress/manifests/nginx-frontend-oasp-deployment.yaml
tests/golden/parts/manifests/mongo-statefulset.yaml
tests/golden/parts/manifests/nginx-frontend-oasp-deployment.yaml
tests/golden/poddisruptionbudget/manifests/nginx-oasp-deployment.yaml
tests/golden/storage-encrypted/manifests/default-oasp-statefulset.yaml
tests/golden/storage-encrypted/manifests/default-shared-oasp-deployment.yaml
tests/golden/storage-encrypted/manifests/share-0-oasp-deployment.yaml
tests/golden/storage-encrypted/manifests/share-1-oasp-deployment.yaml
tests/golden/storage-encrypted/manifests/singleton-db-statefulset.yaml
tests/golden/storage/manifests/default-oasp-statefulset.yaml
tests/golden/storage/manifests/default-shared-oasp-deployment.yaml
tests/golden/storage/manifests/share-0-oasp-deployment.yaml
tests/golden/storage/manifests/share-1-oasp-deployment.yaml
tests/golden/storage/manifests/singleton-db-statefulset.yaml

In the default configuration, Kubernetes will inject a bunch of environment variables for each service in the Namespace. The idea is to aid with service discovery, but while they are rarely used in practice, the injected environment variables might interfere that try to determine their configuration from environment variables.
This commit disables this behaviour by default by setting `enableServiceLinks: false` in the pod specs, but allows users to reenable the links using a label.

feat: Disable Service Links by default

---

docs/conversion.md
pkg/converter/converter.go
tests/golden/storage/compose.yml
tests/golden/storage/manifests/tmpfs-service-oasp-deployment.yaml

Especially when deploying to OpenShift, it is necessary to mount an (ephemeral) emptyDir volume at various places in the file system, to allow a process to write temporary data albeit running under a random user ID.
This commit adds support to define emptyDir volumes using Docker Compose's tmpfs feature [1].
[1]: https://docs.docker.com/reference/compose-file/services/#tmpfs

Add support for mounting `emptyDir` volumes

---

docs/conversion.md
main.go
pkg/converter/converter.go
tests/golden/env-vars/compose.yml
tests/golden/env-vars/manifests/fooBar-oasp-deployment.yaml

Sometimes it's necessary to expose certain pod metadata (e.g. its IP) as
environment variables. To achieve this, Kubernetes provides the
so-called "downward API" [1].
This commit allows users to make use of this API in a similar way we
implemented references to existing secrets.
[1]: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

Add support for "fieldRef" environment variables

---

docs/conversion.md
pkg/converter/converter.go
tests/golden/demo/manifests/mongo-statefulset.yaml
tests/golden/parts/manifests/mongo-statefulset.yaml
tests/golden/storage-encrypted/manifests/default-oasp-statefulset.yaml
tests/golden/storage-encrypted/manifests/singleton-db-statefulset.yaml
tests/golden/storage/manifests/default-oasp-statefulset.yaml
tests/golden/storage/manifests/singleton-db-statefulset.yaml

In order for pods in a STS to "know" their FQDN (instead of just their hostname), the `spec.serviceName` attribute must be set. This will configure their FQDN to be
`${metadata.name}.${spec.serviceName}.${metadata.namespace}.svc.cluster.local`
One example where this is needed is when deploying a MongoDB Replicaset; Pods can only communicate with each other via the FQDN, not their hostnames alone; but they won't recognize "themselves" in the member list when they aren't aware of their own FQDN.

fix: Set `serviceName` on StatefulSets

---

main.go
pkg/converter/converter.go
tests/golden/pre-stop.yml
tests/golden/pre-stop/compose.yml
tests/golden/pre-stop/manifests/nginx-oasp-deployment.yaml
tests/golden/pre-stop/manifests/nginx-oasp-service.yaml

Currently **only** implements command pre_stop lifecycle hook.
https://docs.docker.com/compose/how-tos/lifecycle/
Needed an updated `compose-spec/compose-go` version, as lifecycles weren't part of v1 compose-spec. It was introduced with v2.3.0.
The new v2 compose-spec requires a project name. For POC it is currently hard-coded.
Other than that:
- Only minor changes were needed due to the upgrade, only converter.go's `composeServiceToResourceRequirements` access to `NanoCPUs` changed.

POC service lifecycle hooks

---

pkg/converter/converter.go
pkg/ir/ir.go
tests/golden/service-monitor/compose.yml

* When a service with a partOf annotation referenced a service with an additional partOf annotation, the implementation never worked. It is not intended to have multiple layers of partOf. Therefore, a validation has been put in place to clearly log what is wrong and stop execution.

validate max one partOf
